import { timestamp, uuid } from 'drizzle-orm/pg-core';

/**
 * Shared column definitions.
 *
 * Every table uses the same primary-key and timestamp shape so joins, ordering
 * and auditing behave identically across the schema.
 */

/** UUID primary key generated by Postgres via `gen_random_uuid()` (core since PG13). */
export const primaryId = () => uuid('id').primaryKey().defaultRandom();

/**
 * `timestamptz` everywhere -- never naive timestamps.
 *
 * Metrics are collected from providers and databases in different regions, and
 * comparing them requires an unambiguous instant.
 */
export const timestamps = {
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
};
